<a href="https://colab.research.google.com/github/Sarmentos/challenge-telecom-x-analise-evasao-clientes/blob/main/trabalho.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import math
import sys, os
import numpy as np
import pandas as pd
from google.colab import files

In [36]:
pd.set_option('display.max_columns', 100)

In [37]:
list_missing_values = ["n/a", "na", "undefined"]
dataset = pd.read_csv("https://raw.githubusercontent.com/raulrosapacheco/Dados-Telecom-Analise-Limpeza/main/dados/dataset.csv", na_values = list_missing_values)
dataset.shape

(150001, 55)

In [38]:
dataset.head()

,Bearer Id,Start,Start ms,End,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Last Location Name,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Handset Manufacturer,Handset Type,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
0,1.311448e+19,4/4/2019 12:01,770.0,4/25/2019 14:35,662.0,1823652.0,2.082014e+14,3.366496e+10,3.552121e+13,9.16456699548519E+015,42.0,5.0,23.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,37624.0,38787.0,1.823653e+09,Samsung,Samsung Galaxy A5 Sm-A520F,NaN,NaN,NaN,NaN,NaN,NaN,213.0,214.0,1545765.0,24420.0,1634479.0,1271433.0,3563542.0,137762.0,15854611.0,2501332.0,8198936.0,9656251.0,278082303.0,14344150.0,171744450.0,8814393.0,36749741.0,308879636.0
1,1.311448e+19,4/9/2019 13:04,235.0,4/25/2019 8:15,606.0,1365104.0,2.082019e+14,3.368185e+10,3.579401e+13,L77566A,65.0,5.0,16.0,26.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,168.0,3560.0,1.365104e+09,Samsung,Samsung Galaxy J5 (Sm-J530),NaN,NaN,NaN,NaN,NaN,NaN,971.0,1022.0,1926113.0,7165.0,3493924.0,920172.0,629046.0,308339.0,20247395.0,19111729.0,18338413.0,17227132.0,608750074.0,1170709.0,526904238.0,15055145.0,53800391.0,653384965.0
2,1.311448e+19,4/9/2019 17:42,1.0,4/25/2019 11:58,652.0,1361762.0,2.082003e+14,3.376063e+10,3.528151e+13,D42335A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.361763e+09,Samsung,Samsung Galaxy A8 (2018),NaN,NaN,NaN,NaN,NaN,NaN,751.0,695.0,1684053.0,42224.0,8535055.0,1694064.0,2690151.0,672973.0,19725661.0,14699576.0,17587794.0,6163408.0,229584621.0,395630.0,410692588.0,4215763.0,27883638.0,279807335.0
3,1.311448e+19,4/10/2019 0:31,486.0,4/25/2019 7:36,171.0,1321509.0,2.082014e+14,3.375034e+10,3.535661e+13,T21824A,NaN,NaN,44.0,44.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,3330.0,37882.0,1.321510e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,207.0,644121.0,13372.0,9023734.0,2788027.0,1439754.0,631229.0,21388122.0,15146643.0,13994646.0,1097942.0,799538153.0,10849722.0,749039933.0,12797283.0,43324218.0,846028530.0
4,1.311448e+19,4/12/2019 20:10,565.0,4/25/2019 10:40,954.0,1089009.0,2.082014e+14,3.369980e+10,3.540701e+13,D88865A,NaN,NaN,6.0,9.0,NaN,NaN,100.0,0.0,0.0,0.0,100.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,1.089009e+09,Samsung,Samsung Sm-G390F,NaN,NaN,NaN,NaN,NaN,NaN,607.0,604.0,862600.0,50188.0,6248284.0,1500559.0,1936496.0,173853.0,15259380.0,18962873.0,17124581.0,415218.0,527707248.0,3529801.0,550709500.0,13910322.0,38542814.0,569138589.0

In [39]:
dictionary = pd.read_excel("https://github.com/raulrosapacheco/Dados-Telecom-Analise-Limpeza/blob/main/dados/Dicionario.xlsx?raw=true")
dictionary.shape

(56, 2)

In [40]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150001 entries, 0 to 150000
Data columns (total 55 columns):
 #   Column                                    Non-Null Count   Dtype
---  ------                                    --------------   -----
 0   Bearer Id                                 149010 non-null  float64
 1   Start                                     150000 non-null  object
 2   Start ms                                  150000 non-null  float64
 3   End                                       150000 non-null  object
 4   End ms                                    150000 non-null  float64
 5   Dur. (ms)                                 150000 non-null  float64
 6   IMSI                                      149431 non-null  float64
 7   MSISDN/Number                             148935 non-null  float64
 8   IMEI                                      149429 non-null  float64
 9   Last Location Name                        148848 non-null  object
 10  Avg RTT DL (ms)                           122172 non-null  float64
 11  Avg RTT UL (ms)                           122189 non-null  float64
 12  Avg Bearer TP DL (kbps)                   150000 non-null  float64
 13  Avg Bearer TP UL (kbps)                   150000 non-null  float64
 14  TCP DL Retrans. Vol (Bytes)               61855 non-null   float64
 15  TCP UL Retrans. Vol (Bytes)               53352 non-null   float64
 16  DL TP < 50 Kbps (%)                       149247 non-null  float64
 17  50 Kbps < DL TP < 250 Kbps (%)            149247 non-null  float64
 18  250 Kbps < DL TP < 1 Mbps (%)             149247 non-null  float64
 19  DL TP > 1 Mbps (%)                        149247 non-null  float64
 20  UL TP < 10 Kbps (%)                       149209 non-null  float64
 21  10 Kbps < UL TP < 50 Kbps (%)             149209 non-null  float64
 22  50 Kbps < UL TP < 300 Kbps (%)            149209 non-null  float64
 23  UL TP > 300 Kbps (%)                      149209 non-null  float64
 24  HTTP DL (Bytes)                           68527 non-null   float64
 25  HTTP UL (Bytes)                           68191 non-null   float64
 26  Activity Duration DL (ms)                 150000 non-null  float64
 27  Activity Duration UL (ms)                 150000 non-null  float64
 28  Dur. (ms).1                               150000 non-null  float64
 29  Handset Manufacturer                      140442 non-null  object
 30  Handset Type                              140442 non-null  object
 31  Nb of sec with 125000B < Vol DL           52463 non-null   float64
 32  Nb of sec with 1250B < Vol UL < 6250B     57107 non-null   float64
 33  Nb of sec with 31250B < Vol DL < 125000B  56415 non-null   float64
 34  Nb of sec with 37500B < Vol UL            19747 non-null   float64
 35  Nb of sec with 6250B < Vol DL < 31250B    61684 non-null   float64
 36  Nb of sec with 6250B < Vol UL < 37500B    38158 non-null   float64
 37  Nb of sec with Vol DL < 6250B             149246 non-null  float64
 38  Nb of sec with Vol UL < 1250B             149208 non-null  float64
 39  Social Media DL (Bytes)                   150001 non-null  float64
 40  Social Media UL (Bytes)                   150001 non-null  float64
 41  Google DL (Bytes)                         150001 non-null  float64
 42  Google UL (Bytes)                         150001 non-null  float64
 43  Email DL (Bytes)                          150001 non-null  float64
 44  Email UL (Bytes)                          150001 non-null  float64
 45  Youtube DL (Bytes)                        150001 non-null  float64
 46  Youtube UL (Bytes)                        150001 non-null  float64
 47  Netflix DL (Bytes)                        150001 non-null  float64
 48  Netflix UL (Bytes)                        150001 non-null  float64
 49  Gaming DL (Bytes)                         150001 non-null  float64
 50  Gaming UL (Bytes)                         150001 non-null  float64
 51  Other DL (Bytes)                          150001 non-null  float64
 52  Other UL (Bytes)                          150001 non-null  float64
 53  Total UL (Bytes)                          150000 non-null  float64
 54  Total DL (Bytes)                          150000 non-null  float64
dtypes: float64(50), object(5)
memory usage: 62.9+ MB

In [41]:
dataset.describe()

,Bearer Id,Start ms,End ms,Dur. (ms),IMSI,MSISDN/Number,IMEI,Avg RTT DL (ms),Avg RTT UL (ms),Avg Bearer TP DL (kbps),Avg Bearer TP UL (kbps),TCP DL Retrans. Vol (Bytes),TCP UL Retrans. Vol (Bytes),DL TP < 50 Kbps (%),50 Kbps < DL TP < 250 Kbps (%),250 Kbps < DL TP < 1 Mbps (%),DL TP > 1 Mbps (%),UL TP < 10 Kbps (%),10 Kbps < UL TP < 50 Kbps (%),50 Kbps < UL TP < 300 Kbps (%),UL TP > 300 Kbps (%),HTTP DL (Bytes),HTTP UL (Bytes),Activity Duration DL (ms),Activity Duration UL (ms),Dur. (ms).1,Nb of sec with 125000B < Vol DL,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 37500B < Vol UL,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with Vol DL < 6250B,Nb of sec with Vol UL < 1250B,Social Media DL (Bytes),Social Media UL (Bytes),Google DL (Bytes),Google UL (Bytes),Email DL (Bytes),Email UL (Bytes),Youtube DL (Bytes),Youtube UL (Bytes),Netflix DL (Bytes),Netflix UL (Bytes),Gaming DL (Bytes),Gaming UL (Bytes),Other DL (Bytes),Other UL (Bytes),Total UL (Bytes),Total DL (Bytes)
count,1.490100e+05,150000.000000,150000.000000,1.500000e+05,1.494310e+05,1.489350e+05,1.494290e+05,122172.000000,122189.000000,150000.000000,150000.000000,6.185500e+04,5.335200e+04,149247.000000,149247.000000,149247.000000,149247.000000,149209.000000,149209.000000,149209.000000,149209.000000,6.852700e+04,6.819100e+04,1.500000e+05,1.500000e+05,1.500000e+05,52463.000000,57107.000000,56415.000000,19747.000000,61684.000000,38158.000000,149246.000000,149208.000000,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,150001.000000,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500010e+05,1.500000e+05,1.500000e+05
mean,1.013887e+19,499.188200,498.800880,1.046086e+05,2.082016e+14,4.188282e+10,4.847455e+13,109.795706,17.662883,13300.045927,1770.428647,2.080991e+07,7.596587e+05,92.844754,3.069355,1.717341,1.609654,98.530142,0.776749,0.147987,0.078923,1.144710e+08,3.242301e+06,1.829177e+06,1.408880e+06,1.046091e+08,989.699998,340.434395,810.837401,149.257052,965.464756,141.304812,3719.787552,4022.083454,1.795322e+06,32928.434380,5.750753e+06,2.056542e+06,1.791729e+06,467373.441940,1.163407e+07,1.100941e+07,1.162685e+07,1.100175e+07,4.220447e+08,8.288398e+06,4.211005e+08,8.264799e+06,4.112121e+07,4.546434e+08
std,2.893173e+18,288.611834,288.097653,8.103762e+04,2.148809e+10,2.447443e+12,2.241637e+13,619.782739,84.793524,23971.878541,4625.355500,1.825665e+08,2.645305e+07,13.038031,6.215233,4.159538,4.828890,4.634285,3.225176,1.624523,1.295396,9.631946e+08,1.957064e+07,5.696395e+06,4.643231e+06,8.103761e+07,2546.524440,1445.365032,1842.162008,1219.112287,1946.387608,993.349688,9171.609010,10160.324314,1.035482e+06,19006.178256,3.309097e+06,1.189917e+06,1.035840e+06,269969.307031,6.710569e+06,6.345423e+06,6.725218e+06,6.359490e+06,2.439675e+08,4.782700e+06,2.432050e+08,4.769004e+06,1.127639e+07,2.441429e+08
min,6.917538e+18,0.000000,0.000000,7.142000e+03,2.040471e+14,3.360100e+10,4.400152e+11,0.000000,0.000000,0.000000,0.000000,2.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000e+01,4.000000e+01,0.000000e+00,0.000000e+00,7.142988e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.200000e+01,0.000000,2.070000e+02,3.000000e+00,1.400000e+01,2.000000,5.300000e+01,1.050000e+02,4.200000e+01,3.500000e+01,2.516000e+03,5.900000e+01,3.290000e+03,1.480000e+02,2.866892e+06,7.114041e+06
25%,7.349883e+18,250.000000,251.000000,5.744050e+04,2.082014e+14,3.365130e+10,3.546071e+13,32.000000,2.000000,43.000000,47.000000,3.565150e+04,4.694750e+03,91.000000,0.000000,0.000000,0.000000,99.000000,0.000000,0.000000,0.000000,1.124035e+05,2.432200e+04,1.487775e+04,2.153975e+04,5.744079e+07,20.000000,10.000000,26.000000,2.000000,39.000000,3.000000,87.000000,106.000000,8.991480e+05,16448.000000,2.882393e+06,1.024279e+06,8.927930e+05,233383.000000,5.833501e+06,5.517965e+06,5.777156e+06,5.475981e+06,2.104733e+08,4.128476e+06,2.101869e+08,4.145943e+06,3.322201e+07,2.431068e+08
50%,7.349883e+18,499.000000,500.000000,8.639900e+04,2.082015e+14,3.366371e+10,3.572201e+13,45.000000,5.000000,63.000000,63.000000,5.687300e+05,2.094950e+04,100.000000,0.000000,0.000000,0.000000,100.000000,0.000000,0.000000,0.000000,1.941949e+06,2.297330e+05,3.930450e+04,4.679350e+04,8.639998e+07,128.000000,52.000000,164.000000,8.000000,288.000000,8.000000,203.000000,217.000000,1.794369e+06,32920.000000,5.765829e+06,2.054573e+06,1.793505e+06,466250.000000,1.161602e+07,1.101345e+07,1.164222e+07,1.099638e+07,4.234081e+08,8.291208e+06,4.218030e+08,8.267071e+06,4.114331e+07,4.558411e+08
75%,1.304243e+19,749.000000,750.000000,1.324302e+05,2.082018e+14,3.368349e+10,8.611970e+13,70.000000,15.000000,19710.750000,1120.000000,3.768308e+06,8.402025e+04,100.000000,4.000000,1.000000,0.000000,100.000000,0.000000,0.000000,0.000000,2.504290e+07,1.542827e+06,6.796095e+05,5.990952e+05,1.324308e+08,693.500000,203.000000,757.000000,35.000000,1092.000000,31.000000,2650.000000,2451.000000,2.694938e+06,49334.000000,8.623552e+06,3.088454e+06,2.689327e+06,700440.000000,1.744852e+07,1.651556e+07,1.747048e+07,1.650727e+07,6.331742e+08,1.243162e+07,6.316918e+08,1.238415e+07,4.903424e+07,6.657055e+08
max,1.318654e+19,999.000000,999.000000,1.859336e+06,2.140743e+14,8.823971e+14,9.900120e+13,96923.000000,7120.000000,378160.000000,58613.000000,4.294426e+09,2.908226e+09,100.000000,93.000000,100.000000,94.000000,100.000000,98.000000,100.000000,96.000000,7.253064e+10,1.491890e+09,1.365365e+08,1.449113e+08,1.859336e+09,81476.000000,85412.000000,58525.000000,50553.000000,66913.000000,49565.000000,604061.000000,604122.000000,3.586064e+06,65870.000000,1.146283e+07,4.121357e+06,3.586146e+06,936418.000000,2.325910e+07,2.201196e+07,2.325919e+07,2.201196e+07,8.434419e+08,1.655879e+07,8.434425e+08,1.655882e+07,7.833131e+07,9.029696e+08

In [42]:
dataset.shape

(150001, 55)

In [43]:
dictionary.shape

(56, 2)

In [44]:
df_compare_columns = pd.concat([pd.Series(dataset.columns.tolist()), dictionary['Fields']], axis = 1)
df_compare_columns.rename(columns = {0: 'Dataset Column', 'Fields': 'Dictionary Columns'}, inplace = True)
df_compare_columns

,Dataset Column,Dictionary Columns
0,Bearer Id,bearer id
1,Start,Dur. (ms)
2,Start ms,Start
3,End,Start ms
4,End ms,End
5,Dur. (ms),End ms
6,IMSI,Dur. (s)
7,MSISDN/Number,IMSI
8,IMEI,MSISDN/Number
9,Last Location Name,IMEI
10,Avg RTT DL (ms),Last Location Name
11,Avg RTT UL (ms),Avg RTT DL (ms)
12,Avg Bearer TP DL (kbps),Avg RTT UL (ms)
13,Avg Bearer TP UL (kbps),Avg Bearer TP DL (kbps)
14,TCP DL Retrans. Vol (Bytes),Avg Bearer TP UL (kbps)
15,TCP UL Retrans. Vol (Bytes),TCP DL Retrans. Vol (Bytes)
16,DL TP < 50 Kbps (%),TCP UL Retrans. Vol (Bytes)
17,50 Kbps < DL TP < 250 Kbps (%),DL TP < 50 Kbps (%)
18,250 Kbps < DL TP < 1 Mbps (%),50 Kbps < DL TP < 250 Kbps (%)
19,DL TP > 1 Mbps (%),250 Kbps < DL TP < 1 Mbps (%)
20,UL TP < 10 Kbps (%),DL TP > 1 Mbps (%)
21,10 Kbps < UL TP < 50 Kbps (%),UL TP < 10 Kbps (%)
22,50 Kbps < UL TP < 300 Kbps (%),10 Kbps < UL TP < 50 Kbps (%)
23,UL TP > 300 Kbps (%),50 Kbps < UL TP < 300 Kbps (%)
24,HTTP DL (Bytes),UL TP > 300 Kbps (%)
25,HTTP UL (Bytes),HTTP DL (Bytes)
26,Activity Duration DL (ms),HTTP UL (Bytes)
27,Activity Duration UL (ms),Activity Duration DL (ms)
28,Dur. (ms).1,Activity Duration UL (ms)
29,Handset Manufacturer,Dur. (ms).1
30,Handset Type,Handset Manufacturer
31,Nb of sec with 125000B < Vol DL,Handset Type
32,Nb of sec with 1250B < Vol UL < 6250B,Nb of sec with 125000B < Vol DL
33,Nb of sec with 31250B < Vol DL < 125000B,Nb of sec with 1250B < Vol UL < 6250B
34,Nb of sec with 37500B < Vol UL,Nb of sec with 31250B < Vol DL < 125000B
35,Nb of sec with 6250B < Vol DL < 31250B,Nb of sec with 37500B < Vol UL
36,Nb of sec with 6250B < Vol UL < 37500B,Nb of sec with 6250B < Vol DL < 31250B
37,Nb of sec with Vol DL < 6250B,Nb of sec with 6250B < Vol UL < 37500B
38,Nb of sec with Vol UL < 1250B,Nb of sec with Vol DL < 6250B
39,Social Media DL (Bytes),Nb of sec with Vol UL < 1250B
40,Social Media UL (Bytes),Social Media DL (Bytes)
41,Google DL (Bytes),Social Media UL (Bytes)
42,Google UL (Bytes),YouTube DL (Bytes)
43,Email DL (Bytes),YouTube UL (Bytes)
44,Email UL (Bytes),Netflix DL (Bytes)
45,Youtube DL (Bytes),Netflix UL (Bytes)
46,Youtube UL (Bytes),Google DL (Bytes)
47,Netflix DL (Bytes),Google UL (Bytes)
48,Netflix UL (Bytes),Email DL (Bytes)
49,Gaming DL (Bytes),Email UL (Bytes)
50,Gaming UL (Bytes),Gaming DL (Bytes)
51,Other DL (Bytes),Gaming UL (Bytes)
52,Other UL (Bytes),Other DL
53,Total UL (Bytes),Other UL
54,Total DL (Bytes),Total DL (Bytes)
55,NaN,Total UL (Bytes)

In [45]:
dataset[['Dur. (ms)', 'Dur. (ms).1']]

        Dur. (ms)   Dur. (ms).1
0       1823652.0  1.823653e+09
1       1365104.0  1.365104e+09
2       1361762.0  1.361763e+09
3       1321509.0  1.321510e+09
4       1089009.0  1.089009e+09
...           ...           ...
149996    81230.0  8.123076e+07
149997    97970.0  9.797070e+07
149998    98249.0  9.824953e+07
149999    97910.0  9.791063e+07
150000        NaN           NaN

[150001 rows x 2 columns]

In [46]:
dataset.rename(columns = {'Dur. (ms)': 'Dur (s)',
                          'Dur. (ms).1': 'Dur (ms)',
                          'Start ms': 'Start Offset (ms)',
                          'End ms': 'End Offset (ms)'},
               inplace = True)

dataset.columns.tolist()

['Bearer Id',
 'Start',
 'Start Offset (ms)',
 'End',
 'End Offset (ms)',
 'Dur (s)',
 'IMSI',
 'MSISDN/Number',
 'IMEI',
 'Last Location Name',
 'Avg RTT DL (ms)',
 'Avg RTT UL (ms)',
 'Avg Bearer TP DL (kbps)',
 'Avg Bearer TP UL (kbps)',
 'TCP DL Retrans. Vol (Bytes)',
 'TCP UL Retrans. Vol (Bytes)',
 'DL TP < 50 Kbps (%)',
 '50 Kbps < DL TP < 250 Kbps (%)',
 '250 Kbps < DL TP < 1 Mbps (%)',
 'DL TP > 1 Mbps (%)',
 'UL TP < 10 Kbps (%)',
 '10 Kbps < UL TP < 50 Kbps (%)',
 '50 Kbps < UL TP < 300 Kbps (%)',
 'UL TP > 300 Kbps (%)',
 'HTTP DL (Bytes)',
 'HTTP UL (Bytes)',
 'Activity Duration DL (ms)',
 'Activity Duration UL (ms)',
 'Dur (ms)',
 'Handset Manufacturer',
 'Handset Type',
 'Nb of sec with 125000B < Vol DL',
 'Nb of sec with 1250B < Vol UL < 6250B',
 'Nb of sec with 31250B < Vol DL < 125000B',
 'Nb of sec with 37500B < Vol UL',
 'Nb of sec with 6250B < Vol DL < 31250B',
 'Nb of sec with 6250B < Vol UL < 37500B',
 'Nb of sec with Vol DL < 6250B',
 'Nb of sec with Vol UL < 1250B',
 'Social Media DL (Bytes)',
 'Social Media UL (Bytes)',
 'Google DL (Bytes)',
 'Google UL (Bytes)',
 'Email DL (Bytes)',
 'Email UL (Bytes)',
 'Youtube DL (Bytes)',
 'Youtube UL (Bytes)',
 'Netflix DL (Bytes)',
 'Netflix UL (Bytes)',
 'Gaming DL (Bytes)',
 'Gaming UL (Bytes)',
 'Other DL (Bytes)',
 'Other UL (Bytes)',
 'Total UL (Bytes)',
 'Total DL (Bytes)']

In [47]:
def func_percent_values_missing(df):
  totalCells = np.product(df.shape)
  missingCount = df.isnull().sum()
  totalMissing = missingCount.sum()
  print("O dataset tem", round(((totalMissing/totalCells) * 100), 2), "% de valores ausentes")

In [48]:
def func_percent_values_missing_column(df):
  missingCount = df.isnull().sum()
  missingPercent = 100 * missingCount / len(df)
  missingType = df.dtypes
  missingTable = pd.concat([missingCount, missingPercent, missingType], axis = 1)
  mis_table_ren_columns = missingTable.rename(columns = {0: 'Valores Ausentes', 1: '% de Valores Ausentes', 2: 'Dtype'})
  mis_table_ren_columns = mis_table_ren_columns[mis_table_ren_columns.iloc[:,0] != 0].sort_values('% de Valores Ausentes', ascending = False).round(2)
  print("O dataset tem " + str(df.shape[1]) + " colunas. \nEncontrando: " + str(mis_table_ren_columns.shape[0]) + " colunas que têm valores ausentes.")
  if mis_table_ren_columns.shape[0] == 0:
    return
  return mis_table_ren_columns

In [49]:
def func_percent_values_missing_row(df):
  missing_rows = sum([True for idx,row in df.iterrows() if any(row.isna())])
  total_rows = df.shape[0]
  print(round(((missing_rows/total_rows) * 100), 2), "% das linhas no conjunto de dados contêm pelo menos um valor ausente.")

In [50]:
def fix_missing_ffill(df, col):
  count = df[col].isna().sum()
  df[col] = df[col].fillna(method = 'ffill')
  print(f"{count} valores ausentes na {col} foram substituídos usando método de preenchimento reverso.")
  return df[col]

In [51]:
def fix_missing_bfill(df, col):
    count = df[col].isna().sum()
    df[col] = df[col].fillna(method = 'bfill')
    print(f"{count} valores ausentes na coluna {col} foram substituídos usando o método de preenchimento reverso.")
    return df[col]

In [52]:
def fix_missing_value(df, col, value):
    count = df[col].isna().sum()
    df[col] = df[col].fillna(value)
    if type(value) == 'str':
        print(f"{count} valores ausentes na coluna {col} foram substituídos por '{value}'.")
    else:
        print(f"{count} valores ausentes na coluna {col} foram substituídos por {value}.")
    return df[col]

In [53]:
def drop_rows_with_missing_values(df):
    old = df.shape[0]
    df.dropna(inplace = True)
    new = df.shape[0]
    count = old - new
    print(f"{count} linhas contendo valores ausentes foram descartadas.")

In [54]:
func_percent_values_missing(dataset)

AttributeError: module 'numpy' has no attribute 'product'

In [ ]:
df_missing = func_percent_values_missing_column(dataset)
df_missing

In [ ]:
columns_to_remove = df_missing[df_missing['% de Valores Ausentes'] >= 30.00].index.tolist()
columns_to_remove

In [ ]:
columns_to_remove = [col for col in columns_to_remove if col not in ['TCP UL Retrans. Vol (Bytes)', 'TCP DL Retrans. Vol (Bytes)']]
columns_to_remove

In [ ]:
dataset_clean = dataset.drop(columns_to_remove, axis = 1)
dataset_clean.shape

In [ ]:
func_percent_values_missing(dataset_clean)

In [ ]:
func_percent_values_missing_column(dataset_clean)

In [ ]:
fix_missing_bfill(dataset_clean, 'TCP UL Retrans. Vol (Bytes)')

In [ ]:
fix_missing_bfill(dataset_clean, 'TCP DL Retrans. Vol (Bytes)')

In [ ]:
dataset_clean['Avg RTT DL (ms)'].skew(skipna = True)

In [ ]:
dataset_clean['Avg RTT UL (ms)'].skew(skipna = True)

In [ ]:
fix_missing_ffill(dataset_clean, 'Avg RTT DL (ms)')

In [ ]:
fix_missing_ffill(dataset_clean, 'Avg RTT UL (ms)')

In [ ]:
func_percent_values_missing(dataset_clean)

In [ ]:
func_percent_values_missing_row(dataset_clean)

In [ ]:
func_percent_values_missing_column(dataset_clean)

In [ ]:
fix_missing_value(dataset_clean, 'Handset Type', 'unknown')
fix_missing_value(dataset_clean, 'Handset Manufacturer', 'unknown')

In [ ]:
func_percent_values_missing_row(dataset_clean)

In [ ]:
drop_rows_with_missing_values(dataset_clean)

In [ ]:
func_percent_values_missing(dataset_clean)
dataset_clean.shape

In [ ]:
def convert_to_string(df, columns):
    for col in columns:
        df[col] = df[col].astype("string")

def convert_to_int(df, columns):
    for col in columns:
        df[col] = df[col].astype("int64")

def convert_to_datetime(df, columns):
    for col in columns:
        df[col] = pd.to_datetime(df[col])

def multiply_by_factor(df, columns, factor):
    for col in columns:
        df[col] = df[col] * factor

def drop_duplicates(df):
    old = df.shape[0]
    df.drop_duplicates(inplace = True)
    new = df.shape[0]
    count = old - new
    if (count == 0):
        print("Nenhuma linha duplicada foi encontrada.")
    else:
        print(f"{count} linhas duplicadas foram encontradas e removidas.")

def drop_columns(df, columns):
    df.drop(columns, axis = 1, inplace = True)
    count = len(columns)
    if count == 1:
        print(f"{count} coluna foi descartada.")
    else:
        print(f"{count} colunas foram descartadas.")

In [ ]:
dataset_clean.dtypes

In [ ]:
dataset_clean

In [ ]:
convert_to_datetime(dataset_clean, ['Start', 'End'])

In [ ]:
string_columns = dataset_clean.select_dtypes(include = 'object').columns.tolist()
string_columns

In [ ]:
convert_to_string(dataset_clean, string_columns)

In [ ]:
cols_float_to_int = ['Bearer Id', 'IMSI', 'MSISDN/Number', 'IMEI']
convert_to_int(dataset_clean, cols_float_to_int)

In [ ]:
dataset_clean.dtypes

In [ ]:
drop_duplicates(dataset_clean)

In [ ]:
temp_df = dataset_clean[['Dur (s)', 'Dur (ms)']].copy()
multiply_by_factor(temp_df, ['Dur (ms)'], 1/1000)
temp_df['comparison'] = (temp_df['Dur (s)'] == temp_df['Dur (ms)'].apply(math.floor))
print(temp_df, '\n')

if all(temp_df['comparison']):
  print('Todos os elementos das colunas comparadas são iguais')
else:
  print('As colunas possuem valores diferentes')

In [ ]:
drop_columns(dataset_clean, ['Dur (s)'])

In [ ]:
class handleOutlier:

  def __init__(self, df: pd.DataFrame) -> None:
     self.df = df

  def count_outliers(self, Q1, Q3, IQR, columns):
    cut_off = IQR * 1.5
    temp_df = (self.df[columns] < (Q1 - cut_off)) | (self.df[columns] > (Q3 + cut_off))
    return [len(temp_df[temp_df[col] == True]) for col in temp_df]

  def calc_skew(self, columns=None):
    if columns == None:
      columns = self.df.columns
    return [self.df[col].skew() for col in columns]

  def percentage(self, list):
    return [str(round(((value/150001) * 100), 2)) + '%' for value in list]

  def remove_outliers(self, columns):
    for col in columns:
      Q1, Q3 = self.df[col].quantile(0.25), self.df[col].quantile(0.75)
      IQR = Q3 - Q1
      cut_off = IQR * 1.5
      lower, upper = Q1 - cut_off, Q3 + cut_off
      self.df = self.df.drop(self.df[self.df[col] > upper].index)
      self.df = self.df.drop(self.df[self.df[col] < lower].index)

  def replace_outliers_with_fences(self, columns):
    for col in columns:
      Q1, Q3 = self.df[col].quantile(0.25), self.df[col].quantile(0.75)
      IQR = Q3 - Q1
      cut_off = IQR * 1.5
      lower, upper = Q1 - cut_off, Q3 + cut_off

      self.df[col] = np.where(self.df[col] > upper, upper, self.df[col])
      self.df[col] = np.where(self.df[col] < lower, lower, self.df[col])

  def replace_outliers_with_fences(self, columns):
    for col in columns:
      Q1, Q3 = self.df[col].quantile(0.25), self.df[col].quantile(0.75)
      IQR = Q3 - Q1
      cut_off = IQR * 1.5
      lower, upper = Q1 - cut_off, Q3 + cut_off

      self.df[col] = np.where(self.df[col] > upper, upper, self.df[col])
      self.df[col] = np.where(self.df[col] < lower, lower, self.df[col])

  def getOverview(self, columns) -> None:
    min = self.df[columns].min()
    Q1 = self.df[columns].quantile(0.25)
    median = self.df[columns].quantile(0.5)
    Q3 = self.df[columns].quantile(0.75)
    max = self.df[columns].max()
    IQR = Q3 - Q1
    skew = self.calc_skew(columns)
    outliers = self.count_outliers(Q1, Q3, IQR, columns)
    cut_off = IQR * 1.5
    lower, upper = Q1 - cut_off, Q3 + cut_off

    new_columns = ['Nome de Coluna', 'Min', 'Q1', 'Median', 'Q3', 'Max', 'IQR', 'Lower fence', 'Upper fence', 'Skew', 'Num_Outliers', 'Percent_Outliers' ]

    data = zip([column for column in self.df[columns]], min, Q1, median, Q3, max, IQR, lower, upper, skew, outliers, self.percentage(outliers))

    new_df = pd.DataFrame(data = data, columns = new_columns)

    new_df.set_index('Nome de Coluna', inplace = True)
    \
    return new_df.sort_values('Num_Outliers', ascending = False).transpose()

In [ ]:
handle_outlier = handleOutlier(dataset_clean)

In [ ]:
list_col_float = dataset_clean.select_dtypes('float64').columns.to_list()
list_col_float

In [ ]:
handle_outlier.getOverview(list_col_float)

In [ ]:
handle_outlier.replace_outliers_with_fences(list_col_float)

In [ ]:
handle_outlier.getOverview(list_col_float)

In [ ]:
dataset_clean.info()

In [ ]:

dataset_clean.shape

In [ ]:
dataset_clean.to_csv('dataset_clean.csv', index = False)
files.download('dataset_clean.csv')